[package]

name = "refactor"
version = "0.0.1"
authors = ["Garming <garming_sam@outlook.com>"]

[dependencies]
csv = "0.14.2"

[dependencies.strings]
strings = "0.0.1"
git = "https://github.com/nrc/strings.rs.git"
rev = "b7f37c4545b7dba24fb28161cd9c405fae978be4"
